const CONTACT_ADMIN_CONSTANTS = {
  RESPONSE_HOURS: 24,
  SUBJECT_MIN_CHARS: 5,
  SUBJECT_MAX_CHARS: 200,
  MESSAGE_MIN_CHARS: 20,
  MESSAGE_MAX_CHARS: 5000
};

export default CONTACT_ADMIN_CONSTANTS;
