import LOGIN_FIELD_NAMES from "./Login";
import SIGNUP_FIELD_NAMES from "./Signup";
import FORGOT_PASSWORD_FIELD_NAMES from "./ForgotPassword";
import CHANGE_PASSWORD_FIELD_NAMES from "./ChangePassword";
import SUPPORT_FIELD_NAMES from "./Support";
import ADMIN_APP_FIELD_NAMES from "./AdminApp";
import ADMIN_CONTACT_FILTER_FIELD_NAMES from "./AdminContactFilter";
import ADMIN_LOGIN_HISTORY_FILTER_FIELD_NAMES from "./AdminLoginHistoryFilter";

const FIELD_NAMES = {
  LOGIN_FIELD_NAMES,
  SIGNUP_FIELD_NAMES,
  FORGOT_PASSWORD_FIELD_NAMES,
  CHANGE_PASSWORD_FIELD_NAMES,
  SUPPORT_FIELD_NAMES,
  ADMIN_APP_FIELD_NAMES,
  ADMIN_CONTACT_FILTER_FIELD_NAMES,
  ADMIN_LOGIN_HISTORY_FILTER_FIELD_NAMES
};

export default FIELD_NAMES;
