import LOGIN_FIELD_NAMES from "./Login";
import SIGNUP_FIELD_NAMES from "./Signup";
import FORGOT_PASSWORD_FIELD_NAMES from "./ForgotPassword";
import CONTACT_ADMIN_FIELD_NAMES from "./ContactAdmin";
import ADMIN_APP_FIELD_NAMES from "./AdminApp";
import ADMIN_CONTACT_FILTER_FIELD_NAMES from "./AdminContactFilter";

const FIELD_NAMES = {
  LOGIN_FIELD_NAMES,
  SIGNUP_FIELD_NAMES,
  FORGOT_PASSWORD_FIELD_NAMES,
  CONTACT_ADMIN_FIELD_NAMES,
  ADMIN_APP_FIELD_NAMES,
  ADMIN_CONTACT_FILTER_FIELD_NAMES
};

export default FIELD_NAMES;
