const ERROR_CODES = {
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  CHANGE_PASSWORD_WRONG_CURRENT: "CHANGE_PASSWORD_WRONG_CURRENT",
  CHANGE_PASSWORD_SAME_AS_CURRENT: "CHANGE_PASSWORD_SAME_AS_CURRENT",
  WEB_APP_NAME_EXISTS: "WEB_APP_NAME_EXISTS"
} as const;

export default ERROR_CODES;
