const ROUTES = {
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_OTP: "/forgot-password/otp",
  FORGOT_PASSWORD_MAGIC_LINK: "/forgot-password/magic-link",
  FORGOT_PASSWORD_RESET: "/forgot-password/reset",
  LOGIN: "/login",
  LOGIN_PASSWORD: "/login/password",
  LOGIN_OTP: "/login/otp",
  LOGIN_MAGIC_LINK: "/login/magic-link",
  LOGIN_ALTERNATIVE: "/login/alternative",
  LOGIN_VERIFY_MAGIC_LINK: "/login/verify-magic-link",
  SIGNUP: "/signup",
  SIGNUP_OTP: "/signup/otp",
  SIGNUP_INFO: "/signup/info",
  HOME: "/",
  DISCOVER: "/discover",
  APPS: "/apps",
  FAVORITES: "/favorites",
  RECENTLY_USED: "/recently-used",
  LOGIN_HISTORY: "/login-history",
  PROFILE: "/profile",
  ACCOUNT_SETTINGS: "/account-settings",
  BILLING: "/billing",
  TEAM: "/team",
  SECURITY: "/security",
  NOTIFICATIONS: "/notifications",
  CONTACT_ADMIN: "/contact-admin",
  CONTACT_ADMIN_SUCCESS: "/contact-admin/success",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_APPS: "/admin/apps",
  ADMIN_ENTITLEMENTS: "/admin/entitlements",
  ADMIN_USERS: "/admin/users",
  ADMIN_LOGIN_HISTORY: "/admin/login-history",
  ADMIN_CONTACT: "/admin/contact",
  MY_CONTACTS: "/contacts/me"
};

export default ROUTES;
